import os
import asyncio
from dotenv import load_dotenv
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes
from quote_generator import generate_hinglish_quote
from image_generator import generate_poster

# Load environment variables
load_dotenv()

TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
WATERMARK = os.getenv("WATERMARK", "@realtalks")

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    welcome_message = (
        "Welcome to the Instagram Quote Poster Bot! 🎨\n\n"
        "I can generate aesthetic quote images for your Instagram page.\n\n"
        "Usage: /quote <mood>\n"
        "Examples:\n"
        "/quote sad\n"
        "/quote romantic\n"
        "/quote deep\n"
        "/quote real\n"
        "\nLet's create some amazing content!"
    )
    await update.message.reply_text(welcome_message)

async def quote(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not context.args:
        await update.message.reply_text("Please provide a mood. Example: /quote sad")
        return

    mood = " ".join(context.args)
    status_message = await update.message.reply_text(f"⏳ Generating a '{mood}' quote...")

    try:
        # 1. Generate Quote
        quote_text = await generate_hinglish_quote(mood)
        
        await context.bot.edit_message_text(
            chat_id=update.effective_chat.id,
            message_id=status_message.message_id,
            text=f"🎨 Quote generated! Creating the poster..."
        )
        
        # 2. Generate Image (Running in a thread to not block async loop)
        output_path = f"poster_{update.message.from_user.id}.jpg"
        
        # Use asyncio.to_thread to run synchronous PIL code in background
        await asyncio.to_thread(
            generate_poster, 
            quote_text=quote_text, 
            mood=mood, 
            watermark_text=WATERMARK, 
            output_path=output_path
        )
        
        # 3. Send Image
        caption = f"Here is your {mood} quote! 🌟\n\nGenerated by {WATERMARK}"
        with open(output_path, 'rb') as photo:
            await update.message.reply_photo(photo=photo, caption=caption)
            
        # 4. Cleanup
        await context.bot.delete_message(
            chat_id=update.effective_chat.id,
            message_id=status_message.message_id
        )
        if os.path.exists(output_path):
            os.remove(output_path)
            
    except Exception as e:
        await context.bot.edit_message_text(
            chat_id=update.effective_chat.id,
            message_id=status_message.message_id,
            text=f"❌ An error occurred: {str(e)}"
        )
        print(f"Error in /quote command: {e}")

def main() -> None:
    if not TOKEN:
        print("Error: TELEGRAM_BOT_TOKEN is not set in .env file.")
        return

    application = Application.builder().token(TOKEN).build()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("quote", quote))

    print("Bot is starting...")
    application.run_polling(allowed_updates=Update.ALL_TYPES)

if __name__ == "__main__":
    main()
